# Generated by Django 2.2 on 2021-01-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
