# Generated by Django 2.2 on 2021-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0002_gift_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='status',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
