# Generated by Django 2.2 on 2021-01-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0003_auto_20210109_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='status',
            field=models.BooleanField(),
        ),
    ]
